name: EmanhsCratesPlusOpener
version: 1.0
description: Crate opener for CratesPlus plugin
authors: [ConnorLinfoot, emanh]
website: http://emanhmc.ezyro.com
main: com.ezyro.emanhmc.crateopener.Main
depend: [CratePlus]
loadbefore: [CratePlus]
